setwd("d:/Rprogram/data")
unzip("exdata_data_household_power_consumption.Zip")
power<-read.table("household_power_consumption.txt",header=T, sep=";", na.strings="?")
head(finalpower)
power$Date<-as.character(power$Date)
power$Date<-as.Date(power$Date,"%d/%m/%Y")
power$Time<-as.character(power$Time)
power$Time<-strptime(power$Time,"%T")
a<-as.Date("1/2/2007","%d/%m/%Y")
b<-as.Date("2/2/2007","%d/%m/%Y")
finalpower<-power[power$Date %in% c(a,b),]
hist(finalpower$Global_active_power,main="Global Active Power",xlab="Global Active Power (kilowatts)",col="red")
dev.copy(png,file="plot1.png")
dev.off()
